### ISSUE TITLE
Why is the username-pw-email bar still showing after login?

### ISSUE THREAD

**Issue by q2apro** [jacobwb/hashover#15]
Why is the username-pw-email bar still showing after login?

On top i see the notice, you got logged in. But still there are the login fields. 

From the usability standpoint, they should be hidden after login.

**Comment by jacobwb** [comment]
They remain visible to allow users to change the information before posting. They aren't really "login" fields, they just serve as that for the time being. However, if the user does click the "Login" button the fields should probably be hidden and replaced with a "Logout" or "Edit" button.

This is all temporary. Suggestions are welcomed.

**Comment by q2apro** [comment]
> if the user does click the "Login" button the fields should probably be hidden and replaced with a "Logout" or "Edit" button.

Nope, they are still there. No logout button. 

From the user view, it is (I think) confusing to login and then still see the login fields... of course, they should be hidden after login. This is default behaviour on all websites I know ;)

**Comment by jacobwb** [comment]
Oh, I meant they should be hidden in the future.

Right now, the edit button only shows up if the user has the "login" cookie set on their computer, and the only time the login cookie is set is when they post a comment, so the login button is only there as a way to save the username and password, by setting the login cookie, so that when the initial one expires users can still edit or delete their comments without posting again.

It's the way it is because it isn't an easy thing to fix, not from a technological standpoint, but from a usability standpoint. The idea here is that the user doesn't need an account to comment, likewise they don't need to "Login" either. I have yet to think of a nice way to convey that.

It's a workaround, an ugly one at that, it will be fixed.

**Comment by q2apro** [comment]
Maybe instead of a login, that obviously saves the login data in the xml, we could only show: Username + E-Mail-field, and if the user adds his email he receives an email with a certain code (password) that is added to the URL as a parameter so that hashover can identify him by 1. getting the recent page from the URL in combination with 2. the paramater code (password). 

Just an idea. Also need to think about email abuse and spam.

Another issue I see, with the current version the admin must login to delete or edit the comments. This is why I proposed a separate admin page to manage all comments. Faster and better overview!

**Comment by jacobwb** [comment]
It's insecure to have passwords, encrypted or not, in the URL (GET data), as it's a lot easier for attackers to obtain and use URL parameters than with form data (POST data). Also requiring the user to go to their e-mail every time they want to post is inconvenient.

Aside from that, adding a URL parameter would mean separate comment threads for each with the current URL directory name conversion, and they would be ignored entirely if there were an option to simply ignore all URL parameters like you mentioned earlier.

As for the admin overview, it is planned.

However, the internals of HashOver aren't setup nicely enough where implementing such a feature would be easy. I am working on fixing that, but there's still a lot of work to do.

**Comment by q2apro** [comment]
Okay, agree. That was just a too spontaneous idea.

Maybe it is not important to let the users login anyways in most cases. Edit can be done by admin, or the deletion. And when commenting again, they can specify their email address as an identifier. Maybe sufficient.
