### ISSUE TITLE
Issue while testing Hashover on localhost

### ISSUE THREAD

**Issue by laleksic** [jacobwb/hashover#24]
Placed hashover.php and the hashover/ directory inside ~/public_html; all images are missing (hashover is searching for the images in localhost/hashover/images/ instead of localhost/~laleksic/hashover/images/) and the post comment button doesn't work (again it looks for hashover.php in localhost/ instead of localhost/~laleksic/). How would I go about correcting this?

Edit: Changing $root_dir to './hashover/' from '/hashover/' seems to fix the issue for the avatar image, but not for any other image nor for anything else.

**Comment by taophp** [comment]
HashOver expects to work from the root of the website, `localhost/` in your case, not `localhost/~laleksic`. [Hashover-Next](https://github.com/jacobwb/hashover-next) solved this issue. I think you could give it a try, even if the code is not considered to be "mature" at this time.

**Comment by jacobwb** [comment]
Hello @laleksic

@taophp is correct, HashOver 1.0.x doesn't work from anywhere other than the root of the web server. You likely want to place the `hashover` directory and `hashover.php` file in the same place as the `~laleksic` directory itself is located, and than simply load the script from the root directory.

HashOver 2.0 ([hashover-next](https://github.com/jacobwb/hashover-next)) solved this issue and many, many more, including placing HashOver itself inside a sub-directory inside of `~laleksic` for example. While HashOver 2.0 isn't finished yet and not officially released, it is deliberately kept stable. I would even say it has always been more stable and secure than HashOver 1.0 since the beginning of its development.

Actually, that's the entire purpose of the 2.0 release.

It's safe to use HashOver 2.0.
